#app.yaml
runtime: python37
service: backend
gunicorn: -b :$PORT api3:app

env_variables:
  CLOUD_SQL_USERNAME: picos-sqldev
  CLOUD_SQL_PASSWORD: Picos-23
  CLOUD_SQL_DATABASE_NAME: PiCOS-assesment-results
  CLOUD_SQL_CONNECTION_NAME: deep-span-387504:asia-southeast2:picos-sqldev

handlers:
- url: /.*
  script: auto
```